### ISSUE TITLE
Crash when loading 1.21.4

### ISSUE THREAD

**Issue by NamelessYoungy** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#14]
Bug discovered when testing with MC 1.21.4. Tested using Fabric API 0.112.0+ 1.21.4

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-12-15 12:42:08
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'slabsandstairs' at 'net.frostbyte.slabsandstairs.SlabsAndStairs'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:476)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError
	at knot//net.frostbyte.slabsandstairs.SlabsAndStairs.onInitialize(SlabsAndStairs.java:19)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
Caused by: java.lang.NullPointerException: Item id not set
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at knot//net.minecraft.class_1792$class_1793.method_63689(class_1792.java:251)
	at knot//net.minecraft.class_1792.<init>(class_1792.java:114)
	at knot//net.minecraft.class_1747.<init>(class_1747.java:41)
	at knot//net.frostbyte.slabsandstairs.block.ModBlocks.registerBlockItem(ModBlocks.java:1856)
	at knot//net.frostbyte.slabsandstairs.block.ModBlocks.registerBlock(ModBlocks.java:1851)
	at knot//net.frostbyte.slabsandstairs.block.ModBlocks.<clinit>(ModBlocks.java:18)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:476)

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 363197712 bytes (346 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes
```

**Comment by FrostbyteGames1** [comment]
I haven't yet updated to 1.21.4 as I've been busy with finals. I'm hoping to have all of my mods up to date shortly.

**Comment by FrostbyteGames1** [comment]
v1.12.0 has been published for Minecraft 1.21.4
