### ISSUE TITLE
Sawmill placement is crashing game/server [slabsandstairs-1.6.0.jar]

### ISSUE THREAD

**Issue by gamerpotion** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#7]
Hi one of my users mentioned this and I can confirm it is crashing the game when you place the sawmill
even removing better third person mod, same crash.

Crashlog:-
```---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-08-08 02:02:36
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{slabsandstairs:sawmill}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at net.frostbyte.slabsandstairs.block.custom.SawmillBlock.method_9605(SawmillBlock.java:38)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:272)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.redirect$znd000$betterthirdperson$onDoItemUse(class_310.java:7086)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:130)
	at net.frostbyte.slabsandstairs.block.custom.SawmillBlock.method_9605(SawmillBlock.java:38)
	at net.minecraft.class_1747.method_7707(class_1747.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:75)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:272)
	at net.minecraft.class_636.method_41934(class_636.java:363)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.redirect$znd000$betterthirdperson$onDoItemUse(class_310.java:7086)
	at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
	All players: 1 total; [class_746['GamerPotion'/326, l='ClientLevel', x=4.64, y=63.00, z=-4.34]]
	Chunk stats: 1024, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 11553 game time, 11553 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, elytratrims:default, file/Aimz - Better Crosshair.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2832065368 bytes (2700 MiB) / 5611978752 bytes (5352 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3598
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25033.63
	Virtual memory used (MB): 22024.31
	Swap memory total (MB): 8724.04
	Swap memory used (MB): 675.20
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8096m
	Fabric Mods: 
		additionalstructures: Additional Structures 4.2.0
		advancednetherite: Advanced Netherite 2.0.2-1.20.1
		airchidori: Air Chidori Origin 1.0.5
		alloy_forgery: Alloy Forgery 2.0.22+1.20
		allthetrims: AllTheTrims 3.1.3
		altorigingui: Alternate Origin GUI 1.0.0
		amethyst_core: Amethyst Core 1.2.1+1.20.1
			common-protection-api: Common Protection API 1.0.0
		amethyst_imbuement: Amethyst Imbuement 1.20.1-09
			conditional-mixin: conditional mixin 0.3.2
			fzzy_config: Fzzy Config 0.1.1+1.19.3
			playerabilitylib: Pal 1.8.0
			structurized-reborn: Structurized Reborn 1.20.1-01
		aquachidori: Aqua Chidori Origin 1.0.3
		architectury: Architectury 9.1.12
		armorpointspp: Armorpoints++ 3.1.2
			fiber: fiber 0.23.0-2
		athena: Athena 3.0.0
		azure-paxels: Azure Paxels 1.0.5
		azurelib: AzureLib 1.0.20
			com_eliotlash_mclib_mclib: mclib 20
		beautify: Beautify 1.0.0+1.20
		beekeeperhut: Friends&Foes - Beekeeper Hut 1.3.0
		bettercombat: Better Combat 1.7.3+1.20.1
		betterthirdperson: Better Third Person 1.9.0
		bettertrims: bettertrims 1.2.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		bhmenu: BHMenu-Fabric 1.20.1-2.4.0
		biomemakeover: Biome Makeover 1.20.1-1.10.2
			taniwha: Taniwha 1.20.0-5.1.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.2-1.20
			maelstrom_library: Maelstrom Library 1.6-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		bwncr: Bad Wither No Cookie Reloaded 3.17.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		catalogue: Catalogue 1.7.1
		chipped: Chipped 3.0.1
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		clutter: Clutter 1.20.1-0.3.9
		collective: Collective 6.65
		connectivity: Connectivity Mod 1.20.1-4.4
		controllable: Controllable 0.20.2
			io_github_libsdl4j_libsdl4j: libsdl4j 2.26.4-1.2
		controlling: Controlling For Fabric 12.0.2
		cosmetica: Cosmetica 1.2.5+hotfix
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.11.2
			sulphate: Sulfate 1.1.1
		craftpresence: CraftPresence 2.2.1
		craterlib: CraterLib 1.0.2
		croptopia: Croptopia 2.3.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		crystals_overhauled: Crystals Overhauled 1.3.0
		ctov: ChoiceTheorem's Overhauled Village 3.3.3
		darkbindings: DarkBindings - Custom Recipes 1.3.2
		darkcap: DarkCap - Cap Your XP! 1.0.3
		darkchidori: Dark Chidori Origin 1.0.4
		darkfeather: DarkFeather - Golden Feather 1.0.0
		darkflight: DarkFlight - Simple Jetpack 1.0.4
		darkglint: DarkGlint - Enchantment Glint 1.0.0
		darkheads: DarkHeads- Player Heads 1.0.2
		darkinventory: DarkInventory - Keep Inventory On 1.0.1
		darkloot: DarkLoot - Better Mob Loot 1.1.6
		darkmenu: DarkMenu - DarkRPG Legacy Menu 1.0.7
		darkmining: DarkMining - Better Block Drops 1.0.7
		darkmobs: DarkMobs - Increase Mob Difficulty 1.0.3
		darkorb: DarkOrb - Orb of Origin Recipes 1.0.0
		darkquesting: DarkQuesting - A Quest Mod 1.1.4
		darkrewards: DarkRewards - Item Rewards 1.0.4
		darkrtp: DarkRTP - RTP Teleport 1.0.4
		darksmithing: DarkSmithing - Smithing Template Recipes (for Trims) 1.0.0
		darkspawn: DarkSpawn - Teleport to Spawn 1.0.1
		darkspins: DarkSpins - XP Casino 1.0.6
		darkstarter: DarkStarter - Starter Items 1.0.2
		darktides: DarkTides - Breathe Underwater 1.0.8
		darktimer: DarkTimer - Clear Entity Lag 1.0.5
		darkwaters: Dark Waters 0.0.19
		darkwooly: DarkWooly - Get More Wool 1.0.3
		diamondeconomy: Diamond Economy 1.5.6
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
			placeholder-api: Placeholder API 2.1.1+1.20
		diamondsauctionhouse: Diamond Auction House 1.1.5+1.20
			sgui: sgui 1.2.2+1.20
		digs_dnd_origins: Digs DnD Origins 1.20.1-0.0.11
		dragonloot: DragonLoot 1.1.4
		dungeons_arise: When Dungeons Arise 2.1.56.1
		durability101: Durability101 0.0.4
		elytra-trims-extensions: Elytra Trims Extensions 1.1.1
		elytratrims: Elytra Trims 1.1.9
		emi: EMI 1.0.18+1.20.1+fabric
		emi_loot: EMI Loot 0.6.5+1.20.1
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
		enchantedtooltips: Enchanted ToolTips 1.3.7-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		extraorigins: Extra Origins 1.20-1
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		ferritecore: FerriteCore 6.0.0
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 1.1.0
		forcecrawl: Force Crawl 1.0.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.7
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		friendsandfoes: Friends&Foes 1.9.3
		fwaystones: Fabric Waystones 3.1.2+mc1.20
		fzzy_core: Fzzy Core 0.2.5.1+1.20.1
		geckolib: Geckolib 4.2.1
		geode_plus: Geode+ 1.2.0
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		geophilic: Geophilic v2.0.0-mc1.20u1.20.1
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric
		goldenberry: Golden Berries 1.1.4
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.6
		graveyard: The Graveyard 2.9.1
		grindenchantments: Grind Enchantments 3.1.2+1.20
			codec-config-api: Codec Config API 1.0.2+1.19.3
		handcrafted: Handcrafted 3.0.1
		harvest_scythes: Harvest Scythes 2.5.6+mc1.20
			mm: Manningham Mills 2.3
		healingcampfire: Healing Campfire 5.1
		held-item-info: Held Item Info 1.5.0
		immediatelyfast: ImmediatelyFast 1.1.26+1.20.1
			net_lenni0451_reflect: Reflect 1.2.1
		immersive_aircraft: Immersive Aircraft 0.5.2+1.20.1
		immersive_armors: Immersive Armors 1.6.1+1.20.1
		indium: Indium 1.0.23+mc1.20.1
		inventorysorter: Inventory Sorter 1.9.0-1.20
		iris: Iris 1.6.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.4.3
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.23
		landchidori: Land Chidori Origin 1.0.3
		lazydfu: LazyDFU 0.1.3
		libreexpfix: LibreExpFix 0.1-ALPHA
		limitedspawners: Limited Spawner 1.0.8
		loadingscreentips: Loading Screen Tips 1.3.0
			midnightlib: MidnightLib 1.4.1
		logbegone: Log Begone 1.0.8
		logprot: Logprot Mod 1.20.1-3.0
		lootr: Lootr 0.7.29.75
		malilib: MaLiLib 0.16.1
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwroofs: Macaw's Roofs 2.2.4
		mcwtrpdoors: Macaw's Trapdoors 1.1.1
		menulogue: Menulogue 1.20.1-1.0.4
		midashunger: Midas Hunger 2.2.1+1.20
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		more_armor_trims: More Armor Trims 1.1.0-1.20.1
		morebows: More Bows Restrung 1.0.11+1.20.x
		moremobvariants: More Mob Variants 1.2.2
		mousetweaks: Mouse Tweaks 2.25
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v2.1.4
		mythicmetals: Mythic Metals 0.18.2+1.20
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
		mythicupgrades: Mythic Upgrades +1.9.0-1.20.1
		neruina: Neruina 1.1.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		nohostilesaroundcampfire: No Hostiles Around Campfire 5.6
		nyctophobia: Nyctophobia 1.9
			omega-config: OmegaConfig 1.2.2-1.18.1
		openpartiesandclaims: Open Parties and Claims 0.19.2
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				calio: Calio 1.11.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		origins-classes: Origins: Classes 1.7.0
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-81-FABRIC
		pehkui: Pehkui 3.7.8+1.14.4-1.20.1
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		plentyofarmors: Plenty Of Armors 1.3.0
		plushies: Plushie Mod 1.2.1
		polymorph: Polymorph 0.49.0+1.20.1
			spectrelib: SpectreLib 0.13.13+1.20.1
		puffish_skills: Pufferfish's Skills 0.7.0
		pumpkillagersquest: Pumpkillager's Quest 3.2
		regions_unexplored: Regions Unexplored 0.4.1+1.20.1
		reinfbarrel: Reinforced Barrels 2.4.1+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		reinfchest: Reinforced Chests 2.4.2+1.20
		reinfshulker: Reinforced Shulker Boxes 2.4.1+1.20
		resourcefullib: Resourceful Lib 2.1.9
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		rpg_origins: RPG Origins 1.4.0
		sbaegis-origin: Spellbound Aegis Origin 2.0.0
		sculkedmagpie: Sculked Magpie 1.1
		searchables: Searchables 1.0.1
		servercore: ServerCore 1.3.7+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		showmeyourskin: Show Me Your Skin! 1.6.9+1.20
			cicada: CICADA 0.4.0
		simply_houses: Simply Houses 1.1.4-1.20.1
		simplyswords: Simply Swords 1.51.0-1.20.1
			spruceui: SpruceUI 5.0.0+1.20
		skyvillages: Sky Villages 1.0.2.1-1.20.1
		slabsandstairs: Frostbyte's Slabs & Stairs 1.6.0
		smartbrainlib: SmartBrainLib 1.11.1
		smoothchunk: Smooth chunk save Mod 1.20.1-3.0
		sodium: Sodium 0.5.0
		soulsweapons: Marium's Soulslike Weaponry 0.9.9.6-1.20-fabric
		spark: spark 1.10.42
		starlight: Starlight 1.1.2+fabric.dbc156f
		structureessentials: Structure Essentials Mod 1.20.1-2.9
		terrablender: TerraBlender 3.0.0.169
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.3.1+1.20
			lavender: Lavender 0.1.0-pre.6+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		toms_trading_network: Tom's Trading Network 0.2.3
		toofast: TooFast 1.2.0
		tooltipfix: ToolTip Fix 1.1.1-1.20
		trade_cycling: Trade Cycling 1.20.1-1.0.7
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.2
		trimeffects: Trim Effects 1.0.1-fabric
		trinkets: Trinkets 3.7.1
		utilitybelt: Utility Belt 1.3.3+1.20.x
			tutorial-lib: Tutorial Lib 1.1.2+1.20.x
		walljump: Wall Jump 1.3.6
			org_aeonbits_owner_owner: owner 1.0.12
		wi_zoom: WI Zoom 1.4-MC1.20.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 23.6.0
		xaeroworldmap: Xaero's World Map 1.31.0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 535.98, NVIDIA Corporation
	Window size: 2560x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, elytratrims:default, file/Aimz - Better Crosshair.zip
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['GamerPotion'/326, l='ServerLevel[New World]', x=4.64, y=63.00, z=-4.34]]
	Data Packs: vanilla, fabric, croptopia, darkrpg_quests, darkrpg_quests - Copy, darkrpg_recipes, handcrafted, origin_dolphling, origin_kitsune, origin_warden_hunter, origin_wooly, welcome
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable```

**Comment by FrostbyteGames1** [comment]
Thank you for reporting this, it should now be fixed for version 1.6.1 and beyond.
